### ISSUE TITLE
Adding redirection for static files does not work

### ISSUE THREAD

**Issue by lrscj** [modxcms/Redirector#10]
When testing if target is not a valid object, it should be good to test if it might be a static file.
It would be good to include files in Redirector instead of adding entries in htaccess (limited entries there)
I have static files redirection which can be added only directly in the DB.
eg: patern:   files/de/OSF-Initial-Import_de.pdf  
      target:    files/de/Das-Feature-OSF-Initial-Import.pdf

```
 It works now (they were in DB when upgrade), but I can not add more of this type.
```

Moreover, if there are more contexts having url prefixes (as folders) redirection does not work.

Inter-context redirections do not work either.

**Comment by bertoost** [comment]
File support is implemented

Multi-context with folders is not going to work, because Redirectors' redirect is working on the URI path from the URL. So when you have "example.com/folder/page1.html", Redirector sees "folder/page1.html"...

[closed @jpdevries]

**Comment by lrscj** [comment]
How do I use files redirection? Code checks if an URL is in URI field from DB. 
A file will never appear as URI of a resource.

More than that, I made it work multi-context.
pattern may be from any context; it does not matter which. Code detects from which one.
Target has a certain contact chosen by user. Based on this, target URI is constructed. (of course, target context is mandatory (or default to 'web')
