### ISSUE TITLE
Uninstall error

### ISSUE THREAD

**Issue by bilexes** [modxcms/Redirector#11]
when I tried to remove the redirector php error occurred:
PHP Fatal error:  Call to a member function removeObjectContainer() on a non-object in .../core/packages/redirector-2.0.2-pl/modMenu/c22b79dd638e27b9fda3ac5f8bb5cc1c.resolve.tables.resolver on line 34

In this file uninstall action:

case xPDOTransport::ACTION_UNINSTALL:
    $manager->removeObjectContainer('modRedirect');
break;

but variable $manager is not initialized
should be as follows:

case xPDOTransport::ACTION_UNINSTALL:
    $manager = $modx->getManager();
    $manager->removeObjectContainer('modRedirect');
break;

After this fixes uninstall is working correctly

**Comment by bertoost** [comment]
Fixed in next release.. [closed @jpdevries]
