### ISSUE TITLE
Target URI doesn't exists... Redirect won't work... (MODX Link Tag)

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/Redirector#18]
@bertoost In v2.0.3-pl, this does not seem to be working correctly. If pointing to a Resource a few levels deep, that's also a container, I am receiving this error:
`Target URI doesn't exists... Redirect won't work...`

The Target Resource ID is valid, Published, etc.

It I attempt `[[~1]]` it works, which makes me believe it has to do with nested resources and/or containers?

Related to #2, but not entirely fixed by #3 it seems.

**Comment by bertoost** [comment]
Fixed in next update! Thanks for pointing it out

@jpdevries this can be closed ;-)
