### ISSUE TITLE
Prefer exact match above regex

### ISSUE THREAD

**Issue by RubenKruiswijk** [modxcms/Redirector#20]
Having the following redirects in the Redirector:
- `alias.html` -> `target.html`
- `best-alias.html` -> `best-target.html`

Going to the following URL: 
- `best-alias.html`

Results in a redirect to `target.html` instead of `best-target.html`.

Changing all thousands of existing redirects to `^alias.html$` and `^best-alias.html` could fix the issue, but a better and more easier fix would be to give a preference to the exact match.

https://github.com/modxcms/Redirector/blob/develop/core/components/redirector/elements/plugins/plugin.redirector.php#L26

**Comment by bertoost** [comment]
Thanks for that! Going to investigate (and fix it) asap!

**Comment by bertoost** [comment]
Fix found! Going to release that soon (this morning!)
