### ISSUE TITLE
Import CSV Bug?

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/Redirector#23]
I'm running:

Redirector 2.0.5
MODX Rev 2.2.10
Safari 7.0.3 / Chrome 34.0.1847.116

When I try to bulk upload redirects via the Import CSV tab, uploading a CSV doc, or pasting raw CSV information into the 'Paste raw CSV data here' area and PRESS the 'Start Import' button, nothing happens...

**Comment by bertoost** [comment]
Fixed in next release!
