### ISSUE TITLE
Redirects override default 404 page

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/Redirector#24]
Pattern: 123
Context: blank
Target: http://newurl/newfolder/123
Resource: blank

When I go to http://newurl it redirects to http://newurl/newfolder/123 as expected.

If I type http://newurl/asdadadasdasdasdasdasdasd which should go to the MODX default 404 page, it redirects to http://newurl/newfolder/123!

I have over 100 redirects with the same consistency.

Why is Redirector overriding the default 404 page?

**Comment by Mark-H** [comment]
Could it be because the new Redirector accepts a regex as pattern? It might not be assuming there's an end..

**Comment by jonleverrier** [comment]
This could well be the case. How do I add an end to my '123' pattern via regex so I can test?

**Comment by eighthday** [comment]
The 404 error page stopped working for me after I installed Redirector, I have had to uninstall.

**Comment by markwillis82** [comment]
This looks the REGEXP part of the where clause gets removed from the SQL injection fixes placed in MODx 2.2.13+.

So the SQL ends up pulling the first object out the database from the remaining where clauses.

This functionality needs to be re-written and tested.

```
$q = $modx->newQuery('modRedirect');
$q->where(array(
    "('".$search."' REGEXP `modRedirect`.`pattern` OR '".$search."' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))",
     "(`modRedirect`.`context_key` = '".$modx->context->get('key')."' OR `modRedirect`.`context_key` IS NULL OR `modRedirect`.`context_key` = '')",
         'active' => true,
    ));
$q->prepare();
echo $q->toSQL();
```

**Comment by kkruzel** [comment]
If you don't need the regex matching in your redirects, you can just remove few lines in the plugin source and the 404 will work as before.

In your manager, click on Plugins ->redicector and remove these lines (starting at line 33):

```
        if(empty($redirect) || !is_object($redirect)) {
            $redirect = $modx->getObject('modRedirect', array(
                "('".$search."' REGEXP `modRedirect`.`pattern` OR '".$search."' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))",
                "(`modRedirect`.`context_key` = '".$modx->context->get('key')."' OR `modRedirect`.`context_key` IS NULL OR `modRedirect`.`context_key` = '')",
                'active' => true,
            ));
        }
```

**Comment by bertoost** [comment]
I will dive into it when I do have some time (soon I hope)

**Comment by faitno** [comment]
kkruzel - Wow! it work! now my 404 page work again!

**Comment by markwillis82** [comment]
I've added #27 This resolves the problem by moving the regex tests to php rather than in the database.

**Comment by apathyuk** [comment]
I have tried uncommenting the lines as suggested by kkruzel 4 entries above but I am still getting 404 being redirected using an existing rule.  Do I need to make any other changes?  I am running 2.2.14 on modxcloud.com

UPDATE: I made the change to components/redirector/elements/plugins/plugin.redirector.php rather than to the plugin directly.  The later worked.

**Comment by salscode** [comment]
Thank you kkruzel, did your fix and it worked. I don't need REGEX but I need a 404 page.

**Comment by jasonabird** [comment]
Same thing here, Didn't dive deep into this to fully fix but I'm not using REGEX, just need the 404 to work so commented out the code.

**Comment by ghost** [comment]
I have the same problem on this. The url redirects correctly but the 404 pages doesn't work anymore. 

Tried to remove the code on line 33 and the 404 page works again but the redirect fails to work.

I don't know why I need to remove a line for the 404 page to work again either.

Are there any other solutions?

**Comment by kosmonowt** [comment]
Great! Thank you. Excluding the code as shown above just works!

**Comment by bertoost** [comment]
Update 2.0.6 coming soon. Fixed!

**Comment by adamwintle** [comment]
Finally good to have a fix for this! :)
