### ISSUE TITLE
Patch required

### ISSUE THREAD

**Issue by lrscj** [modxcms/Redirector#26]
I have a website with 3 Contexts - one per language
Old version of Redirector permits resource IDs for target. In my case, context folder is doubles in this case. A patch is helpful in this case. It should just replace [[~id]] with actual URI.
Moreover, pattern needs also to be updated and context filled in by old pattern value. (Context may be retrieved from pattern)
There are also issues with REGEXP when pageNotFound event occurs. Modx raises an error like this:
Error parsing condition with key 0: ('entreprise.html' REGEXP `modRedirect`.`pattern` OR 'entreprise.html' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))

It is because MODX does not recognize REGEXP as operator.

And Redirectior is still incomplete by pattern testing. What about if it is an existing file? It is not enough to check in the DB.

Poor quality code.

**Comment by crimsonpixel** [comment]
Hi Bert - looks as if I'm getting the same error messages appearing:

[2014-06-04 15:37:47](ERROR @ /index.php) Error parsing condition with key 0: ('assets/themes/js/lang/en.js' REGEXP `modRedirect`.`pattern` OR 'assets/themes/js/lang/en.js' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))

I've attached some of my entries. Did also try ^wp-content\/uploads\/(.*) - but still got errors.

![redirector](https://cloud.githubusercontent.com/assets/2063237/3175034/7e419ec4-ebf7-11e3-8b70-604baa3a9f86.png)

**Comment by lrscj** [comment]
More over, pattern is not checked for file existence. The pattern may exist on disk, and I am not notified that redirect would not work.

**Comment by bertoost** [comment]
But the beauty is; the redirector plugin is only loaded when MODX throws a "OnPageNotFound" event. This means that the URL entered in the browser isn't found on the disk, or as MODX resource. When the file is on the disk, and you're sure about the path, maybe something is wrong with your .htaccess (or NginX setup)?

**Comment by crimsonpixel** [comment]
So is the example I've set up correct? I've set up a 404 page, as a result because the incorrect pages are going to this 404 it means they are finding a page on the server and as a result the redirector won't work....? Is this the reason for the errors? For the average person setting up these redirects is not easy if they do not understand any sort of programming. The original redirector enabled you to add the url without any additional regex characters and simply redirected to new page. Or am I missing something here? :)

**Comment by bertoost** [comment]
That's still possible. The new Redirector also supports regex pattern/target urls.
The setup of a 404 page is something different than making redirects.
When MODX returns a 404, also the "OnPageNotFound" event is fired. Redirector is binded to that event, so he can search the database to see if the URL should be redirected. When it found a record, it will redirect. When not, you will see your 404 page (at least; not when some other plugin captured it).

**Comment by lrscj** [comment]
@bertoost 
I don't get it about "the beauty" of Redirector. 

> But the beauty is; the redirector plugin is only loaded when MODX throws a "OnPageNotFound"  event. This means that the URL entered in the browser isn't found on the disk, or as MODX resource. When the file is on the disk, and you're sure about the path, maybe something is wrong with your .htaccess (or NginX setup)?

If I want to add a redirection, and the file still exists by mistake on disk, why shouldn't I be notified the redirection will not work? I am notified about resources; it should be same for files on disk.

**Comment by crimsonpixel** [comment]
Ok so checking my set up using Redirector, I've set up from old site any URLs which were listed previously as news/photo-gallery/ to go directly to page gallery/ and whilst I can see in the redirector this is clearly firing

![redirector](https://cloud.githubusercontent.com/assets/2063237/3297448/9c2e1ce6-f5f2-11e3-84ff-e8a0086f05f2.png)

And my error log is now full of these errors (and more!):

[2014-06-17 07:04:03](ERROR @ /index.php) Error parsing condition with key 0: ('gallery/support-us/' REGEXP `modRedirect`.`pattern` OR 'gallery/support-us/' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))
[2014-06-17 07:05:20](ERROR @ /index.php) Error parsing condition with key 0: ('gallery/donate.html' REGEXP `modRedirect`.`pattern` OR 'gallery/donate.html' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))

**Comment by lrscj** [comment]
This is just because MODX does not know about REGEXP. 
Go to /core/xpdo/om/xpdoquery.class.php and at the beginning of file you will fine the list of operators (REGEXP not included).
I have manually added REGEXP and it works, but this is not a good idea. 
So, this is it.

**Comment by crimsonpixel** [comment]
Ok, I'll give that a go. In my example would the simple "news/photo-gallery/" (without any REGEXP) go  to the page "gallery/"? I'm pretty sure when I used it still gave errors.

**Comment by bertoost** [comment]
that should work indeed

**Comment by bmilton** [comment]
Trying to follow this thread...I am getting errors as of the 2.0.5 release.  The same regex patterns that worked in 2.0.4 do not work any longer.

ex: 

pattern: Storage-Container-Quote.html(.*)$
target: storage-container-quote$1

Causes a redirect loop and error in log.  I've reverted back to 2.0.4.  Is an update planned?

**Comment by crimsonpixel** [comment]
Added the REGEXP as suggested by @lrscj and that worked.

**Comment by bertoost** [comment]
Fixed in 2.0.6. Update coming soon
