### ISSUE TITLE
Error thrown when creating redirects for the same pattern with different contexts

### ISSUE THREAD

**Issue by wosephjeber** [modxcms/Redirector#34]
I encountered an issue this morning as I was setting up a redirect. Our MODX Revo site has multiple contexts running, and I needed to set up redirects for the pattern "blog" to redirect to different targets based on the context. I created the redirect for the first context with no trouble, but received an error message each time I tried to create the second redirect using the same pattern but with a different context key. I was looking through the `create.class.php` file, and I could see that the the component was supposed to allow duplicate patterns as long as the context key was different. I finally realized the error was being returned after Redirector attempted to save the redirect to the database.

I checked the error log and it had this statement: 

```
[2014-08-26 11:28:34] (ERROR @ /assets/components/redirector/connector.php) Error 23000 executing statement:
INSERT INTO `modx_redirects` (`pattern`, `target`, `context_key`, `active`) VALUES ('blog', '[[~1542]]', 'australia', 1)
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry 'blog' for key 'pattern'
)
```

Looking at the database table, I noticed the `pattern` column was set with a `UNIQUE` key. Removing that key solved the problem.

Our site was initially using version 1.0.1, and we updated from that directly to 2.0.5. That version has an open issue (#24) that is overriding the 404 page setting, so I reverted to 2.0.4. I'm guessing the `UNIQUE` key was a legacy feature of the original installed version, and I'm not sure if this is something that can be addressed in the transport package for new versions or if this is just an edge case. Either way, I wanted to point it out so that it's documented in case anyone else runs into the same issue.

**Comment by bertoost** [comment]
This works in the latest version. Probably an old bug. Try again in the upcoming 2.0.6 and report again if still fails
