### ISSUE TITLE
When using 2 simelar url's only one is working:

### ISSUE THREAD

**Issue by dimmy01** [modxcms/Redirector#35]
want to redirect the folloing url's:

winkels/uw-telecomexpert.html -> [[~116]]
winkels/uw-telecomexpert/uw-telecomexpert-geldrop.html  -> [[~58]]

but both go to  [[~116]],
when I disable the first redirect the 2nd redirect works as expected.

looks like the patern check is to lose?

**Comment by bertoost** [comment]
Works as expected in the new upcoming 2.0.6
