### ISSUE TITLE
Import CSV Fails - Firefox & Chrome

### ISSUE THREAD

**Issue by computer-legacy** [modxcms/Redirector#37]
The browsers:

Mozilla Firefox 31.0
Google Chrome 37.0.2062.124
Using Redirector 2.05-pl.

Importing CSV data fails, button doesn't seem to work.

Firefox Console:
TypeError: formObj.isValid is not a function - home.panel.js:115
Chrome Console:
Uncaught TypeError: undefined is not a function - home.panel.js:115

Attempted Fixes:
Cleared site cache.
Cleared browser cache.
Reinstalled application.

**Comment by jopberkhout** [comment]
Yup, I've got the same error. The CSV upload is not working. I'm hosting the website on MODX Cloud. Might that be the issue?

MacBook Pro (2014 model)
Google Chrome Versie 40.0.2214.115 (64-bit)
Using Redirector 2.0.5-pl

# Chrome console

Uncaught TypeError: undefined is not a function - home.panel.js:115
it.push.items.handler - home.panel.js:115 
Ext.Button.Ext.extend.onClick - ext-all.js:21
I - ext-all.js:21

# Attempted fixes

Cleared site cache

**Comment by PabloDeGrote** [comment]
Apparently this is already fixed in the develop branch:

https://github.com/modxcms/Redirector/blob/develop/assets/components/redirector/js/mgr/widgets/home.panel.js

Copy this content of the file above and replace it @ `/assets/components/redirector/js/mgr/widgets/home.panel.js` to get it working

**Comment by bertoost** [comment]
Probably already fixed. Please test again in the upcoming 2.0.6 and report again if it still not works.
