### ISSUE TITLE
Target as [[~id]] not accepted after site move

### ISSUE THREAD

**Issue by craigphiz** [modxcms/Redirector#50]
I just moved a MODX Revolution 2.3.2-pl site from a subfolder, where the development was happening, to the root of the host. 

All seemed to be working well apart from when I came to add or update a redirect. Redirector was working well before the move with Targets set as `[[~id]]` (eg `[[~12]]`) but now the error `Target URI doesn't exist... Redirect won't work...` appears when trying to save or update a redirect. 

All the existing redirects with Target set as `[[~id]]` are redirecting okay. New redirects with Targets as aliases, eg help.html, are saving.

Tried a few things... and lastly: Uninstalled Redirector, removed from Package Manager. Dropped the modx_redirects table, cleared the cache and then reinstalled Redirector. Issue persists.

Is anyone else seeing this? Any suggestions greatly appreciated :)

**Comment by markryder** [comment]
Yes, I've installed from new and am also seeing this behaviour. Any id is rejected as invalid, alias are accepted.

**Comment by craigphiz** [comment]
I'm still seeing this issue too. The only way I've found to add new ids is to add them directly in the modx_redirects database table.

**Comment by markryder** [comment]
Thanks for the tip!

**Comment by bertoost** [comment]
Cannot reproduce this. Adding it and redirecting without any harms... Try the new 2.0.6 soon!
