### ISSUE TITLE
id in old link is honoured

### ISSUE THREAD

**Issue by markryder** [modxcms/Redirector#51]
Appears that if your old URL pattern was something like this:
index.php?option=com_content&task=view&id=25&Itemid=30
then even though you create a redirection to a new alias, the page is redirected to whatever resource on the new site that has that old id number, so in this case it will redirect to resource 25 and not the resource specified.

This was using the pattern
^index.php?option=com_content&task=view&id=25&Itemid=30$

In fact it will redirect to whatever resource id on the new site has the old id, whether or not it is published.

**Comment by bertoost** [comment]
Issue closed.
That's because MODX uses ?id=x too.
Since that's a core feature, Redirector will not be triggered because it will not end up in a "page not found" event.
