### ISSUE TITLE
DB table not created during clean install

### ISSUE THREAD

**Issue by ghost** [modxcms/Redirector#6]
```
Console running...
Attempting to install package with signature: redirector-2.0.1-pl
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Could not create table `modx_redirects` SQL: CREATE TABLE `modx_redirects` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `pattern` VARCHAR(255) NOT NULL DEFAULT '', `target` VARCHAR(255) NOT NULL DEFAULT '', `context_key` VARCHAR(255) NULL, `active` TINYINT(1) unsigned NOT NULL DEFAULT '1', PRIMARY KEY (`id`), INDEX `pattern_context` (`pattern`,`context_key`), INDEX `target` (`target`), INDEX `active` (`active`)) ENGINE=MyISAM ERROR: Array ( [0] => 42000 [1] => 1071 [2] => Specified key was too long; max key length is 1000 bytes ) 
```

Looks like the pattern_context index on 2 varchars causes this.

**Comment by bertoost** [comment]
Something to do with the index column lengths.. they are not respected in xPDO. I reported that here https://github.com/modxcms/xpdo/issues/33

Also; removed the unique index to avoid this error and not creating db table.
Update coming soon!

**Comment by markwillis82** [comment]
Are you using a UTF8 charset?

There is a maximum length for indexes. This may be getting hit with the 2 columns of 255 varchars

**Comment by bertoost** [comment]
I know. But the length attribute of the index definition isn't respected by xPDO. See my previous comment where I put the link in to the bug report for that.
Also working on it to get an update released in a couple of minutes

**Comment by bertoost** [comment]
Fixed! Released update a minute ago ;-)

**Comment by bertoost** [comment]
Close it for me @jpdevries :-)
