### ISSUE TITLE
Fix ​Potential BlindSQL Injection

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/Redirector#60]
With help from Vasiliy we found the issue was with the Redirector plugin when the rare case of not found page and injection in url happens...

We fixed the issue and I wil submit a issue for the plugin https://github.com/modxcms/Redirector.

filter request in plugin

`$search = rawurldecode($_SERVER['REQUEST_URI']);`

replace to

```
$search = rawurldecode($_SERVER['REQUEST_URI']);
$search = preg_replace('#\(.*?\)+#', '', $search);
```

https://forums.modx.com/thread/100421/need-help-with-potential-blindsql-injection#dis-post-542701

**Comment by Jako** [comment]
Maybe it is better to change the $c->where clauses to something that is escaped by xPDO by default. Or do a `$searchEscape = $modx->quote($search);` and use that value in the query generation.

**Comment by rthrash** [comment]
Feel like making a proper PR on this one Jako?

**Comment by Jako** [comment]
Done …

**Comment by Jako** [comment]
BUMP!
