### ISSUE TITLE
Failed as hacking vector but targeted massively

### ISSUE THREAD

**Issue by goldsky** [modxcms/Redirector#65]
I have a proof about a hacking attempt through this package.
If you are interested, email me for detail.

**Comment by Jako** [comment]
Those blind sql injection attempts were fixed with: https://github.com/modxcms/Redirector/commit/f2ac28c8678089fcf30f517ab35add37048deccf

**Comment by goldsky** [comment]
are you releasing the new package into extras repo?

**Comment by Jako** [comment]
It was released as 2.0.8 containing the patch.

**Comment by goldsky** [comment]
Ok, that's funny, because I'm using 2.0.8.

**Comment by Jako** [comment]
Before the patch, the hacking vector was successful. Now the package should contain the changed code. Doesn't it?
