### ISSUE TITLE
Error after upgrading to MODX 2.7.0

### ISSUE THREAD

**Issue by Camo30** [modxcms/Redirector#68]
This error shows up in the error log after upgrading MODX:

> [2018-11-30 19:40:14] (ERROR in modMenu::getSubMenus @ /www/htdocs/modx/core/model/modx/modmenu.class.php : 145) modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace redirector to the routing based system.

**Comment by Jako** [comment]
It is still a valid issue.

**Comment by Camo30** [comment]
That's correct, but I believed that your forked repo is the current one.

**Comment by Jako** [comment]
No, I am not the maintainer of this repository. Even if it looks like this.

**Comment by Jako** [comment]
2.0.9 finally arrived in the MODX Extras repository
