### ISSUE TITLE
Strange (wrong) processing of the pattern

### ISSUE THREAD

**Issue by OceanITs** [modxcms/Redirector#71]
**Examle pattern**
```
paneli
```

**Must matches only**
```
https://somesite.com/paneli
```

**Also matches**
```
https://somesite.com/paneli/images
https://somesite.com/assets/images/paneli/109/03.jpg
https://somesite.com/assets/images/products/109/paneli-03.jpg (if not img exists)
etc..
```

**Solution**

core/components/redirector/elements/plugins/redirector.plugin.php (in Plugin)
line (44) Remove 
```
( OR " . $searchEscape . " REGEXP `modRedirect`.`pattern` )
```

**Please check! Maybe I misunderstood something**

**Comment by Jako** [comment]
```paneli``` matches every occurring word in the url, since it is used as a regular expression. If you want to target only an url ```https://somesite.com/paneli```, you have to create a regular expression for this: ```^/paneli$```.
